fix allocating empty proof
matter-labs/snark-wrapper pull request #8
Opened 2023-09-26 15:34 UTC by olesHolem

2023-09-26 15:37 UTC, akash-chandrakar submitted a review, later dismissed

2023-09-26 15:37 UTC, shamatar requested changes

2023-09-26 22:05 UTC, shamatar commented on src/verifier_structs/mod.rs
> +    debug_assert!(source.as_mut().map(|el| el.next()).flatten().is_none());
I would be careful with “flatten”. We do not expect to have Some(None) or reverse, but still. You may prefer to have “expect” inside of “map” here and above

2023-09-27 09:43 UTC, akash-chandrakar submitted a review, later dismissed

2023-09-27 11:45 UTC, shamatar submitted a review, later dismissed

2023-09-28 11:23 UTC, akash-chandrakar approved these changes

2023-09-28 11:24 UTC, merged